<a href="https://colab.research.google.com/github/julihdez36/Machine_learning/blob/main/Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is PyTorch?

https://docs.pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

PyTorch is a Python-based scientific computing package serving two broad purposes:

1. A replacement for NumPy to use the power of GPUs and other accelerators.

2. An automatic differentiation library that is useful to implement neural networks.

## Tensor
Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other specialized hardware to accelerate computing. If you’re familiar with ndarrays, you’ll be right at home with the Tensor API. If not, follow along in this quick API walkthrough.


In [ ]:
import torch
import numpy as np

In [ ]:
# Tensor initialization

# from data

data = [list(range(5)),list(range(5,10))]
x_data = torch.tensor(data)

x_data

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# From numpy array

np_array = np.arange(0,10).reshape(2,5)
x_np = torch.from_numpy(np_array) # Memory sharing (faster)
# torch.tensor(np_array) # Creates a copy of the data
x_np

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# From another tensor

torch.ones_like(x_data) # retains the properties of x_data

torch.rand_like(x_data, dtype= torch.float) # overrides the datatype of x_data

tensor([[0.2340, 0.3501, 0.9705, 0.9125, 0.6066],
        [0.0128, 0.4628, 0.6726, 0.3924, 0.2749]])

In [ ]:
# With random or constant values

shape = (2,3,)

ten1 = torch.rand(shape)
ten2 = torch.ones(shape)
ten3 = torch.zeros(shape)

ten1, ten2, ten3

(tensor([[0.6956, 0.9712, 0.6494],
         [0.0358, 0.7871, 0.2061]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [ ]:
# Tansor attributes
# Like an arrya we can get shape and dtype

tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f'Dimention of tensor: {tensor.ndim}')
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Dimention of tensor: 2
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
# Tensor operations

# Each of them (operations) can be run on the GPU (at typically higher speeds than on a CPU).

# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

print(f"Device tensor is stored on: {tensor.device}")


Device tensor is stored on: cpu


In [ ]:
tensor = torch.ones(4,4)
print(tensor)

tensor[:,2] = 0
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]])


In [ ]:
# Joining tensors

# torc.cat to concatenate a sequence of tensors

t1 = torch.cat([tensor,tensor,tensor], dim = 1) # dim: along which axis you want to concatenate
print(t1)

tensor([[1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.],
        [1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.],
        [1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.],
        [1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.]])


In [ ]:
tensor2 = torch.tensor([[3,5],
                       [7,6]])
t2 = torch.cat([tensor2, tensor2], dim = 0) # rows, stack downwards
t3 = torch.cat([tensor2, tensor2], dim = 1) # columns, stack side by side

t2, t3


(tensor([[3, 5],
         [7, 6],
         [3, 5],
         [7, 6]]),
 tensor([[3, 5, 3, 5],
         [7, 6, 7, 6]]))

In [ ]:
# other way

x = torch.randn(2,3)
torch.stack((x,x))

tensor([[[-0.1781,  2.1236, -1.4354],
         [ 0.2579, -0.6767, -0.3457]],

        [[-0.1781,  2.1236, -1.4354],
         [ 0.2579, -0.6767, -0.3457]]])

In [ ]:
torch.stack((x, x), dim=2) # creates a new dimension

tensor([[[-0.1781, -0.1781],
         [ 2.1236,  2.1236],
         [-1.4354, -1.4354]],

        [[ 0.2579,  0.2579],
         [-0.6767, -0.6767],
         [-0.3457, -0.3457]]])

In [ ]:
# Multiplying tensors

# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]]) 

tensor * tensor 
 tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]])
