# Operaciones con matrices

## Suma de matrices y del producto por escalares

La suma de dos matrices A y B del mismo tamaño es la matriz A+B uya entrda (i,j) es
$$[A+B]_{ij} = a_{ij} + b_{ij}$$

In [11]:
import numpy as np

def create_matriz(low = -10, high =10,size = (2,2)):
    return np.random.randint(low = low, high= high, size = size)


In [12]:
A = create_matriz(size = (3,3))
B = create_matriz(size = (3,3))

print(A)
print(B)


[[-9  8  7]
 [ 3 -5 -3]
 [ 5 -5 -8]]
[[-7 -2  9]
 [-1  9  8]
 [-1  9  2]]


In [13]:
print(A+B)

[[-16   6  16]
 [  2   4   5]
 [  4   4  -6]]


El producto de un escalar $\lambda$ por una matriz $\lambda A$ cuya entrada $(i,j)$ es

$$[\lambda A]_{ij} = \lambda a_{ij}$$

In [18]:
escalar = 3
escalar * A

array([[-27,  24,  21],
       [  9, -15,  -9],
       [ 15, -15, -24]])

### Leyes de la suma de matrices y del producto poe escalares

Sean $A,B \in \mathcal{M}_{mxn}(\mathbb{K})$ La suma de matrices cumple las siguientes propiedades:
1. Asociativa: $(A+B)+C = A+(B+C)$
2. Conmutativa: $A+B = B+A$
3. Elemento neutro: $A+0_{mxn} = A$
4. Elemento opuesto: $A+(-A) = 0_{mxn}$

Y el producto por escalares cumplen:
5. Distributiva respecto a la suma de matrices: $\alpha (A+B) = \alpha A + \alpha B$
6. Distributiva respecto de la suma de escalares: $(\alpha + \beta)A = \alpha A + \beta A$
7. Asociativa con respecto del producto por escalares: $(\alpha \beta) A = \alpha (\beta A)$
8. Unidad del cuerpo, $1 \in \mathbb{K}$, cumple que $1A = A$

### Producto de matrices

El producto de dos matrices tiene sentido si el número de columnas de la primera es igual al número de fila de la segunda. Dadas las matrices $A \in \mathcal{M}_{mxn}(\mathbb{K})$ y $A \in \mathcal{M}_{nxp}(\mathbb{K})$, el producto $AB$ es la matriz de tamaño $mxp$ cuya entrada $(i,j)$ se obtiene multiplicando la fila $i$ de $A$ por la columna $j$ de $B$ según la regla:

$$[AB]_{ij} = F_{i}(A)C_{j}B = \sum_{k=1}^{n} a_{ik}b_{kj}$$

In [ ]:
def matrix_product(A,B):
    for i in A:
        for j in:
        A[]


In [19]:
A = create_matriz()
A

array([[-1,  7],
       [-8,  0]])

In [23]:
A[:1,:2]

array([[-1,  7]])

In [29]:
len(create_matriz(size = (4,3)))

4

In [28]:
create_matriz(size = (4,3))

array([[-1, -4, -2],
       [ 8,  3,  8],
       [ 4, -6,  7],
       [ 1, -1,  2]])