# Operaciones con matrices

## Suma de matrices y del producto por escalares

La suma de dos matrices A y B del mismo tamaño es la matriz A+B uya entrda (i,j) es
$$[A+B]_{ij} = a_{ij} + b_{ij}$$

In [1]:
import numpy as np

def create_matriz(low = -10, high =10,size = (2,2)):
    return np.random.randint(low = low, high= high, size = size)


In [2]:
A = create_matriz(size = (3,3))
B = create_matriz(size = (3,3))

print(A)
print(B)


[[ 1  7 -8]
 [-6 -3  0]
 [ 0  6 -3]]
[[ -1   1   1]
 [-10  -9   6]
 [ -2  -3  -3]]


In [3]:
print(A+B)

[[  0   8  -7]
 [-16 -12   6]
 [ -2   3  -6]]


El producto de un escalar $\lambda$ por una matriz $\lambda A$ cuya entrada $(i,j)$ es

$$[\lambda A]_{ij} = \lambda a_{ij}$$

In [4]:
escalar = 3
escalar * A

array([[  3,  21, -24],
       [-18,  -9,   0],
       [  0,  18,  -9]])

### Leyes de la suma de matrices y del producto poe escalares

Sean $A,B \in \mathcal{M}_{mxn}(\mathbb{K})$ La suma de matrices cumple las siguientes propiedades:
1. Asociativa: $(A+B)+C = A+(B+C)$
2. Conmutativa: $A+B = B+A$
3. Elemento neutro: $A+0_{mxn} = A$
4. Elemento opuesto: $A+(-A) = 0_{mxn}$

Y el producto por escalares cumplen:
5. Distributiva respecto a la suma de matrices: $\alpha (A+B) = \alpha A + \alpha B$
6. Distributiva respecto de la suma de escalares: $(\alpha + \beta)A = \alpha A + \beta A$
7. Asociativa con respecto del producto por escalares: $(\alpha \beta) A = \alpha (\beta A)$
8. Unidad del cuerpo, $1 \in \mathbb{K}$, cumple que $1A = A$

### Producto de matrices

El producto de dos matrices tiene sentido si el número de columnas de la primera es igual al número de fila de la segunda. Dadas las matrices $A \in \mathcal{M}_{mxn}(\mathbb{K})$ y $A \in \mathcal{M}_{nxp}(\mathbb{K})$, el producto $AB$ es la matriz de tamaño $mxp$ cuya entrada $(i,j)$ se obtiene multiplicando la fila $i$ de $A$ por la columna $j$ de $B$ según la regla:

$$[AB]_{ij} = F_{i}(A)C_{j}B = \sum_{k=1}^{n} a_{ik}b_{kj}$$

In [5]:
print(A)
print(A[:1,:2])

[[ 1  7 -8]
 [-6 -3  0]
 [ 0  6 -3]]
[[1 7]]


In [6]:
len(create_matriz(size = (4,3)))

4

In [7]:
A =np.array([[3,2],
                [4,1]])
B = np.array([[0,1],
                [2,3]])

print(A, B)


[[3 2]
 [4 1]] [[0 1]
 [2 3]]


In [8]:
A@B

array([[4, 9],
       [2, 7]])

In [9]:
C = np.zeros((2,2))

C[0,0] = A[0,0]*B[0,0] +A[0,1] * B[1,0]
C[0,1] = A[0,0]*B[0,1] +A[0,1] * B[1,1]

C[1,0] = A[1,0]*B[0,0] +A[1,1] * B[1,0]
C[1,1] = A[1,1]*B[0,1] +A[0,1] * B[1,1]

C

array([[4., 9.],
       [2., 7.]])

In [10]:
C = np.zeros((2,2))

for i in range(2):
    for j in range(2):
        C[i,j] = A[i,0]*B[0,j] +A[i,1] * B[1,j]

C

array([[4., 9.],
       [2., 7.]])

In [11]:
# Podemos generalizarlo

import numpy as np

def prod_matricial(A, B):
    if A.shape[1] != B.shape[0]:
        raise ValueError("Las dimensiones no coinciden: columnas de A != filas de B")
    
    C = np.zeros((A.shape[0], B.shape[1]))
    
    # Recorremos filas de A y columnas de B
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            # Aquí implementamos el producto punto de la fila i y la columna j
            # Usando el tercer bucle k para la sumatoria general
            for k in range(A.shape[1]):
                C[i, j] += A[i, k] * B[k, j]
                
    return C

In [12]:
prod_matricial(A,B)

array([[4., 9.],
       [2., 7.]])

### Leyes del producto de matrices

Sean $A \in \mathcal{M}_{mxn} (\mathbb{K}), B,C \in \mathcal{M}_{nxp} (\mathbb{K}), D \in \mathcal{M}_{pxq} (\mathbb{K})$ y $\alpha \in \mathbb{K}$. El producto cumple las leyes:
1. Asociativa: $(AB)D = A(BD)$
2. Existencia de elemento neutro por la derecha: $AI_{n} = A$
3. Existencia de elemento neutro por la izquierda: $I_{m}A = A$
4. Asociatividad respecto del producto por escalares: $\alpha (AB) = (\alpha A)B = A (\alpha B)$
5. Distributiva respecto de la suma de matrices por la derecha: $A(B+C) = AB + AC$ 
6. Distributiva respecto de la suma de matrices por la izquierda: $(B+C)D = BD + CD$

Nótese que el producto AB con B escalar 


 $$
\begin{pmatrix}
a_{11} & \cdots & a_{1n} \\
\vdots & \ddots & \vdots \\
a_{m1} & \cdots & a_{mn}
\end{pmatrix}
\begin{pmatrix}
b_{11} \\
\vdots \\
b_{n1}
\end{pmatrix}
= b_{11}
\begin{pmatrix}
a_{11} \\
\vdots \\
a_{m1}
\end{pmatrix}
+ \cdots + b_{n1}
\begin{pmatrix}
a_{1n} \\
\vdots \\
a_{mn}
\end{pmatrix}
$$


In [13]:
A = np.array([[2,1,1],
             [1,0,1],
             [2,2,1],
             [3,1,1]])
B = np.array([[-2,4,3]]).reshape(3,1)
print(A)
print(B)

[[2 1 1]
 [1 0 1]
 [2 2 1]
 [3 1 1]]
[[-2]
 [ 4]
 [ 3]]


## Las potencias de una matriz cuadrada

La potencia $k-ésima$ de una matriz $A \in \mathcal{M}_{n} (\mathbb{K})$ es el producto de $A$ por sí misma $k$ veces

$$A^{k} = A \cdots A$$

Por convenio $A^{0} = I{n}$

Algunas matrices cuadradas tinene un comportamiento especial con respecto a la potencia.
- $A \in \mathcal{M}_{n} (\mathbb{K})$ es **idempotente** si $A^2 = A$
- $A \in \mathcal{M}_{n} (\mathbb{K})$ es **nilpotente** si $\exists k \in \mathbb{Z} > 0 : A^k = 0$
- $A \in \mathcal{M}_{n} (\mathbb{K})$ es **involutiva** si $\exists k \in \mathbb{Z} > 0 : A^2 = I_{n}$


Para las matrices diagonales es especialmente sencillo calcular sus potencias:

$$A = diag(d_{1},d_{2}, \dots ,d_{n}) \Rightarrow A^{K} = diag(d_{1}^{k}, d_{2}^{k}, \dots, d_{n}^{k})$$

In [14]:
# Nótese que la matriz identidad es idempotente

A = np.eye(3)
A*A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Matriz idempotente

A = np.array([[-3,-4,-8],
              [1,2,2,],
              [1,1,3]])

A@A

array([[-3, -4, -8],
       [ 1,  2,  2],
       [ 1,  1,  3]])

In [ ]:
# Matriz nilpotente 

B = np.array([[],
              [],
              []])