# Operaciones con matrices

## Suma de matrices y del producto por escalares

La suma de dos matrices A y B del mismo tamaño es la matriz A+B uya entrda (i,j) es
$$[A+B]_{ij} = a_{ij} + b_{ij}$$

In [1]:
import numpy as np

def create_matriz(low = -10, high =10,size = (2,2)):
    return np.random.randint(low = low, high= high, size = size)


In [2]:
A = create_matriz(size = (3,3))
B = create_matriz(size = (3,3))

print(A)
print(B)


[[-5  1 -3]
 [-2  0  3]
 [-9 -1  7]]
[[ 1 -4  5]
 [ 5 -4 -9]
 [ 1 -4  3]]


In [3]:
print(A+B)

[[-4 -3  2]
 [ 3 -4 -6]
 [-8 -5 10]]


El producto de un escalar $\lambda$ por una matriz $\lambda A$ cuya entrada $(i,j)$ es

$$[\lambda A]_{ij} = \lambda a_{ij}$$

In [4]:
escalar = 3
escalar * A

array([[-15,   3,  -9],
       [ -6,   0,   9],
       [-27,  -3,  21]])

### Leyes de la suma de matrices y del producto poe escalares

Sean $A,B \in \mathcal{M}_{mxn}(\mathbb{K})$ La suma de matrices cumple las siguientes propiedades:
1. Asociativa: $(A+B)+C = A+(B+C)$
2. Conmutativa: $A+B = B+A$
3. Elemento neutro: $A+0_{mxn} = A$
4. Elemento opuesto: $A+(-A) = 0_{mxn}$

Y el producto por escalares cumplen:
5. Distributiva respecto a la suma de matrices: $\alpha (A+B) = \alpha A + \alpha B$
6. Distributiva respecto de la suma de escalares: $(\alpha + \beta)A = \alpha A + \beta A$
7. Asociativa con respecto del producto por escalares: $(\alpha \beta) A = \alpha (\beta A)$
8. Unidad del cuerpo, $1 \in \mathbb{K}$, cumple que $1A = A$

### Producto de matrices

El producto de dos matrices tiene sentido si el número de columnas de la primera es igual al número de fila de la segunda. Dadas las matrices $A \in \mathcal{M}_{mxn}(\mathbb{K})$ y $A \in \mathcal{M}_{nxp}(\mathbb{K})$, el producto $AB$ es la matriz de tamaño $mxp$ cuya entrada $(i,j)$ se obtiene multiplicando la fila $i$ de $A$ por la columna $j$ de $B$ según la regla:

$$[AB]_{ij} = F_{i}(A)C_{j}B = \sum_{k=1}^{n} a_{ik}b_{kj}$$

In [5]:
def matrix_product(A,B):
    for i in A:
        for j in:
        A[]


SyntaxError: invalid syntax (1475611326.py, line 3)

In [ ]:
A = create_matriz()
A

array([[-1,  7],
       [-8,  0]])

In [ ]:
A[:1,:2]

array([[-1,  7]])

In [ ]:
len(create_matriz(size = (4,3)))

4

In [ ]:
create_matriz(size = (4,3))

array([[-1, -4, -2],
       [ 8,  3,  8],
       [ 4, -6,  7],
       [ 1, -1,  2]])

In [17]:
A@B

array([[ -3,  28, -43],
       [  1,  -4,  -1],
       [ -7,  12, -15]])

In [24]:
resultados = np.zeros(shape=(A.shape[0],B.shape[1]))

for i in range(A.shape[1]):
    suma = []
    for j in range(A.shape[0]):
        coeficiente = suma.append(A[i,j] * B[j,i])
    resultados[i,j] = coeficiente

resultados

array([[ 0.,  0., nan],
       [ 0.,  0., nan],
       [ 0.,  0., nan]])

In [ ]:
# 1. Definimos las dimensiones
filas_A = A.shape[0]
cols_A = A.shape[1]   # Debe ser igual a filas_B
cols_B = B.shape[1]

resultados = np.zeros((filas_A, cols_B))

# 2. Triple bucle
for i in range(filas_A):          # Recorre cada FILA de A
    for j in range(cols_B):      # Recorre cada COLUMNA de B
        suma_acumulada = 0
        for k in range(cols_A):  # El índice compartido (pivote)
            # Multiplicamos elemento de fila i por elemento de columna j
            suma_acumulada += A[i, k] * B[k, j]
        
        resultados[i, j] = suma_acumulada


-3