# Método de Gauss

Se describe el proceso de transformación de una matriz medinate la realización de transformaciones en sus filas denominadas operaciones elementales.Con este procedimiento convertiremos la matriz original en una amtriz escalonada en la que determinaremos propiedades de la matriz original más facilmente. La propiedad fundamental que se estudiará es la dependencia o independencia lineal de sus filas.

::: {.callout-note}
## Definición: Combinación lineal

Sea $F_{1}, \dots, F_{K} \in \mathcal{M}$ matrices filas. La matriz fila
$$F = \alpha_{1} F_{1} + \dots + \alpha_{k} F_{k}, \hspace{2mm} \alpha_{i} \in {\mathbb{K}}$$

es una combinación lineal de $F_{1} \dots F_{K}$ con coeficientes $\alpha_{1}, \dots, \alpha_{k}$.

Las matrices fila $F_{1}, \dots, F_{K}$ son **dependientes** (o linealmente dependientes) si alguna de ellas es combinación lineal de las demás. En caso contrario se dice que $F_{1} \dots F_{k}$ son **independientes** (o linealmente independientes).
:::



In [2]:
import numpy as np

A = np.array([[0,0,1,3],
              [3,6,1,2],
              [1,2,0,1],
              [0,0,3,5]])

# probemos una combinación lineal sobre f4
# f4 = 2*f1 + f2 - 3*f3

f4 = 2*A[0,:] + A[1,:] - 3*A[2,:]
f4

# Las filas de A son dependientes, dado que F4 es combinación lineal de F1,F2 yF3

array([0, 0, 3, 5])


Sea $F_{1}, \dots, F_{K} \in \mathcal{M}$ matrices filas del mismo tamaño, entonces $F_{1}, \dots, F_{K} \in \mathcal{M}$ son **dependientes linealmente** si y solo si existen escalares $\alpha_{1}, \dots , \alpha{k}$, no todos nulos, tales que:

$$\alpha_{1}F_{1} + \cdots  \alpha_{k}F_{k} = 0$$

Una combinación **lineal trivial** de matrices fila es aquella en la que todos los coeficientes $\alpha$ son 0

### Operaciones elementales de filas. Matrices elementales

Las transformaciones que se pueden aplican a una matriz en el conocido como método de Gauus se denominan **opraciones elementales de filas** son de tres tipos:

- **Tipo I:** intercambio de las filas $i$ y $j$, se denota $f_{i} \leftrightarrow f_{j}$
- **Tipo II:** Sumar a la fila $i$ la fila $j$ multiplicada por un escalar. Se denota $f_{i} \rightarrow fi + \alpha f_{j}$
- **Tipo III:** Multiplicar la fila $i$ por un escalar no nulo. Se denota $f_{i} \rightarrow \alpha f_{i}$ con $\alpha \neq 0$


Asociadas a las operaciones elementales de filas están las denominadas mtrices elementales.

::: {.callout-note}
## Definición: 
Una **matriz elemental** de orden $n$ es una matriz resultante de aplicar a la matriz identidad $I_{n}$ una operación elemental de filas. Las hay de tres tipos:
- $E_{f_{i} \leftrightarrow f_{j}}$
- $E_{f_{i} \rightarrow fi + \alpha f_{j}}$
- $E_{f_{i} \rightarrow \alpha f_{i}}$
:::

Realizar una operación elemental en las filas de una matriz $A$ es equivalente a multiplicar $A$ por la izquierda por la matriz elemental que corresponde a dicha operación elemental.


In [3]:
def E_1(A,fi,fj):
    A_n = A.copy().astype(float)
    A_n[[fi,fj]] = A_n[[fj,fi]]
    return A_n 

A = np.eye(4)

E_1(A,0,2)

array([[0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [4]:
def E_2(A,fi,fj,alpha):
    A_n = A.copy().astype(float)
    A_n[fi] = A_n[fi] + alpha*A_n[fj]
    return A_n

A = np.eye(4)

E_2(A,2,0,alpha= 2)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [2., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
def E_3(A,fi,alpha):
    A_n = A.copy().astype(float)
    A_n[fi] = alpha * A_n[fi]
    return A_n

A = np.eye(4)

E_3(A,1,alpha= 2)

array([[1., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
A = np.array([[0,2,2],
              [2,0,4],
              [1,-1,3],
              [0,1,2]])

I = np.eye(4)

In [7]:
A_n = E_1(A,0,2)
E1 = E_1(I,0,2)

print(A_n)

[[ 1. -1.  3.]
 [ 2.  0.  4.]
 [ 0.  2.  2.]
 [ 0.  1.  2.]]


In [8]:
A_n = E_2(A_n,1,0,alpha = -2)
E2 = E_2(I,1,0,alpha = -2)

print(A_n)

[[ 1. -1.  3.]
 [ 0.  2. -2.]
 [ 0.  2.  2.]
 [ 0.  1.  2.]]


In [9]:
A_n = E_3(A_n,1,alpha=(1/2))
E3 = E_3(I,1,alpha=(1/2))

print(A_n)

[[ 1. -1.  3.]
 [ 0.  1. -1.]
 [ 0.  2.  2.]
 [ 0.  1.  2.]]


In [10]:
# Nótese que esta matriz se puede construir multiplicando por la izquierda las matrices elementales

E3@E2@E1@A

array([[ 1., -1.,  3.],
       [ 0.,  1., -1.],
       [ 0.,  2.,  2.],
       [ 0.,  1.,  2.]])

### Matrices escalonadas y escalonadas reducidas

El primer elemento no nulo de cada una de las filas de una matriz se denomina **pivote**. Una fila nula no tiene pivote. 

::: {.callout-note}
## Definición: 
La matriz $A$ es escalonada (o escalonada por filas) si cumple las siguientes propiedades:
- Si $A$ tiene $k$ filas nulas, éstas son las $k$ últimas
- Todo pivote de $A$ tiene más ceros a su izquierda que el pivote de la fila anterior. Como es lógico, esta propiedad no afecta al pivote de la primera fila.

La matriz $A$ es escalonada reducida si es escalonada y además cumple que:
- Todos los pivotes de $A$ son iguales a 1
- Toda entrada de $A$ situada en la misma columna que un pivote es igual a 0
:::

Nótese que:
1. la mariz núla es escalonada y escalonada reducida.
2. La úica matriz escalonada reducida de orden $n$ con $n$ filas no nulas es la identidad $I_n$

### Matrices equivalentes por filas

cuando aplicamos una sucesión de operaciones elementales de filas a una matriz estamos estableciendo una conexión entre la matriz original y la matriz final.

:::{.callout-note}
## Definición
Dos matrices $A,B \in \mathcal{M}_{mxn}(\mathbb{K}) $ son equivalentes por filas si $A \sim_{f} B$, si $A=B$ o si se puede transformar $A$ en $B$ mediante una sucesión finita de operaciones elementales de filas. Esta última propiedad es igual a decir que existen matrices elementales $E_{1}, \dots , E_{k}$ tales que $B = E_{k} \cdots E_{1} A$
:::

Si transformamos una matriz $A$ en $B$ aplicando una operación elementa, podemos invertir el proceso y transformar $B$ en $A$ aplicando la **operación elemental inversa**.

La existencia de las operaciones elementales inversas permite establecer una relación de equivalencia. 


In [11]:
A = np.array([[0,-3,3],
              [2,6,0],
              [1,-3,2]])

B = np.array([[1,-3,2],
              [0,12,-4],
              [0,0,2]])
A,B

(array([[ 0, -3,  3],
        [ 2,  6,  0],
        [ 1, -3,  2]]),
 array([[ 1, -3,  2],
        [ 0, 12, -4],
        [ 0,  0,  2]]))

In [23]:
A1 = E_1(A, 0, 2)
A2 = E_2(A1,1,0,-2)
A3 = E_2(A2,2,1,1/4)

A3 == B

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [14]:
A[2]

array([ 1, -3,  2])

In [ ]:
# Lo que realmente comparten las matrices equivalentes es su forma escalonada reducida por filas (RREF). Si dos matrices tienen la misma RREF, son equivalentes.
import sympy as sp

A.rref() == B.rref()

True

## Combinación lineal de filas en matrices equivalentes por filas
p. 38

¿Es A equivalente a B?: True
