# Método de Gauss

Se describe el proceso de transformación de una matriz medinate la realización de transformaciones en sus filas denominadas operaciones elementales.Con este procedimiento convertiremos la matriz original en una amtriz escalonada en la que determinaremos propiedades de la matriz original más facilmente. La propiedad fundamental que se estudiará es la dependencia o independencia lineal de sus filas.

::: {.callout-note}
## Definición: Combinación lineal

Sea $F_{1}, \dots, F_{K} \in \mathcal{M}$ matrices filas. La matriz fila
$$F = \alpha_{1} F_{1} + \dots + \alpha_{k} F_{k}, \hspace{2mm} \alpha_{i} \in {\mathbb{K}}$$

es una combinación lineal de $F_{1} \dots F_{K}$ con coeficientes $\alpha_{1}, \dots, \alpha_{k}$.

Las matrices fila $F_{1}, \dots, F_{K}$ son **dependientes** (o linealmente dependientes) si alguna de ellas es combinación lineal de las demás. En caso contrario se dice que $F_{1} \dots F_{k}$ son **independientes** (o linealmente independientes).
:::



In [1]:
import numpy as np

A = np.array([[0,0,1,3],
              [3,6,1,2],
              [1,2,0,1],
              [0,0,3,5]])

# probemos una combinación lineal sobre f4
# f4 = 2*f1 + f2 - 3*f3

f4 = 2*A[0,:] + A[1,:] - 3*A[2,:]
f4

# Las filas de A son dependientes, dado que F4 es combinación lineal de F1,F2 yF3

array([0, 0, 3, 5])


Sea $F_{1}, \dots, F_{K} \in \mathcal{M}$ matrices filas del mismo tamaño, entonces $F_{1}, \dots, F_{K} \in \mathcal{M}$ son **dependientes linealmente** si y solo si existen escalares $\alpha_{1}, \dots , \alpha{k}$, no todos nulos, tales que:

$$\alpha_{1}F_{1} + \cdots  \alpha_{k}F_{k} = 0$$

Una combinación **lineal trivial** de matrices fila es aquella en la que todos los coeficientes $\alpha$ son 0

### Operaciones elementales de filas. Matrices elementales

Las transformaciones que se pueden aplican a una matriz en el conocido como método de Gauus se denominan **opraciones elementales de filas** son de tres tipos:

- **Tipo I:** intercambio de las filas $i$ y $j$, se denota $f_{i} \leftrightarrow f_{j}$
- **Tipo II:** Sumar a la fila $i$ la fila $j$ multiplicada por un escalar. Se denota $f_{i} \rightarrow fi + \alpha f_{j}$
- **Tipo III:** Multiplicar la fila $i$ por un escalar no nulo. Se denota $f_{i} \rightarrow \alpha f_{i}$ con $\alpha \neq 0$


Asociadas a las operaciones elementales de filas están las denominadas mtrices elementales.

::: {.callout-note}
## Definición: 
Una **matriz elemental** de orden $n$ es una matriz resultante de aplicar a la matriz identidad $I_{n}$ una operación elemental de filas. Las hay de tres tipos:
- $E_{f_{i} \leftrightarrow f_{j}}$
- $E_{f_{i} \rightarrow fi + \alpha f_{j}}$
- $E_{f_{i} \rightarrow \alpha f_{i}}$
:::

Realizar una operación elemental en las filas de una matriz $A$ es equivalente a multiplicar $A$ por la izquierda por la matriz elemental que corresponde a dicha operación elemental.


In [2]:
def E_1(A,fi,fj):
    A_n = A.copy().astype(float)
    A_n[[fi,fj]] = A_n[[fj,fi]]
    return A_n 

A = np.eye(4)

E_1(A,0,2)

array([[0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [3]:
def E_2(A,fi,fj,alpha):
    A_n = A.copy().astype(float)
    A_n[fi] = A_n[fi] + alpha*A_n[fj]
    return A_n

A = np.eye(4)

E_2(A,2,0,alpha= 2)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [2., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
def E_3(A,fi,alpha):
    A_n = A.copy().astype(float)
    A_n[fi] = alpha * A_n[fi]
    return A_n

A = np.eye(4)

E_3(A,1,alpha= 2)

array([[1., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
A = np.array([[0,2,2],
              [2,0,4],
              [1,-1,3],
              [0,1,2]])

I = np.eye(4)

In [6]:
A_n = E_1(A,0,2)
E1 = E_1(I,0,2)

print(A_n)

[[ 1. -1.  3.]
 [ 2.  0.  4.]
 [ 0.  2.  2.]
 [ 0.  1.  2.]]


In [7]:
A_n = E_2(A_n,1,0,alpha = -2)
E2 = E_2(I,1,0,alpha = -2)

print(A_n)

[[ 1. -1.  3.]
 [ 0.  2. -2.]
 [ 0.  2.  2.]
 [ 0.  1.  2.]]


In [8]:
A_n = E_3(A_n,1,alpha=(1/2))
E3 = E_3(I,1,alpha=(1/2))

print(A_n)

[[ 1. -1.  3.]
 [ 0.  1. -1.]
 [ 0.  2.  2.]
 [ 0.  1.  2.]]


In [9]:
# Nótese que esta matriz se puede construir multiplicando por la izquierda las matrices elementales

E3@E2@E1@A

array([[ 1., -1.,  3.],
       [ 0.,  1., -1.],
       [ 0.,  2.,  2.],
       [ 0.,  1.,  2.]])

### Matrices escalonadas y escalonadas reducidas

El primer elemento no nulo de cada una de las filas de una matriz se denomina **pivote**. Una fila nula no tiene pivote. 

::: {.callout-note}
## Definición: 
La matriz $A$ es escalonada (o escalonada por filas) si cumple las siguientes propiedades:
- Si $A$ tiene $k$ filas nulas, éstas son las $k$ últimas
- Todo pivote de $A$ tiene más ceros a su izquierda que el pivote de la fila anterior. Como es lógico, esta propiedad no afecta al pivote de la primera fila.

La matriz $A$ es escalonada reducida si es escalonada y además cumple que:
- Todos los pivotes de $A$ son iguales a 1
- Toda entrada de $A$ situada en la misma columna que un pivote es igual a 0
:::

Nótese que:
1. la mariz núla es escalonada y escalonada reducida.
2. La úica matriz escalonada reducida de orden $n$ con $n$ filas no nulas es la identidad $I_n$

### Matrices equivalentes por filas

cuando aplicamos una sucesión de operaciones elementales de filas a una matriz estamos estableciendo una conexión entre la matriz original y la matriz final. Si transformamos una matriz $A$ en $B$ aplicando una operación elemental, podemos invertir el proceso y transformar $B$ en $A$ aplicando la **operación elemental inversa**.

:::{.callout-note}
## Definición
Dos matrices $A,B \in \mathcal{M}_{mxn}(\mathbb{K}) $ son equivalentes por filas si $A \sim_{f} B$, si $A=B$ o si se puede transformar $A$ en $B$ mediante una sucesión finita de operaciones elementales de filas. Esta última propiedad es igual a decir que existen matrices elementales $E_{1}, \dots , E_{k}$ tales que $B = E_{k} \cdots E_{1} A$
:::

In [10]:
A = np.array([[0,-3,3],
              [2,6,0],
              [1,-3,2]])

B = np.array([[1,-3,2],
              [0,12,-4],
              [0,0,2]])
A,B

(array([[ 0, -3,  3],
        [ 2,  6,  0],
        [ 1, -3,  2]]),
 array([[ 1, -3,  2],
        [ 0, 12, -4],
        [ 0,  0,  2]]))

In [11]:
A1 = E_1(A, 0, 2)
A2 = E_2(A1,1,0,-2)
A3 = E_2(A2,2,1,1/4)

A3 == B

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Nótese que la equivalencia puede probarse através de la forma escalonada reducida por filas (RREF). Si dos matrices tienen la misma RREF, son equivalentes. Esto se puede hacer con sympy, una libreria de matematica simbolica.

In [12]:
import sympy 

A_s = sympy.Matrix(A)

A_s.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

In [13]:
B_s = sympy.Matrix(B)
B_s.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

## Combinación lineal de filas en matrices equivalentes por filas

Supongamos que $A$ se tranforma en $B$ mediante una operación elementarl de filas. Dado que las operaciones elemtales se dan sobre una fila $f_{i}$ de $A$, se puede verificar que la fila $i$ de $B$ que obtenemos es combinación lineal de filas de $A$.

:::{.callout-note}
Si $A \sim_{f} B$ entones oda fila de $B$ es combinación lineal de filas de $A$.
:::

Las operaciones elementales de filas para alcanzar la forma escalonada reducida lo que hace es detectar y transformar en nulas aquellas filas que sean combinación lineal del resto. Al final del proceso se llega a una matriz escalonada cuyas filas no nulas son independientes. De esto se deriva que 

:::{.callout-note}
## Teorema
Toma matriz es equivalente por filas a una matriz escalonada.
:::

El proceso de llevar una matriz a su forma escalonada a través de las operaciones elementales por filas se conoce como **método de escalonamiento de Gauss** o **método de Gauss**.

En forma de algorítmo podemos alcanzar la forma escalonada utilizando únicamente operaciones elementales de **Tipo I** y **II**:

1. Buscamos la primera columna de $A$ que tenga algún elemento distinto de $0$. Supongamos que es la columna $j$. Buscamos en esta columna $j$ de $A$ el primer elemento distinto de $0$. Supongamos que éste se encuentra en la fila $h$ y que es igual a $\lambda \neq 0$. Entonces aplicamos la operación elemental de **Tipo I**: $f_1 \leftrightarrow f_h$ y obtenemos una matriz que tiene un pivote igual a $\lambda$ en la posición $(1, j)$.

2. Para cada $i \neq 1$ sea $\gamma$ el elemento que se encuentra en la posición $(i, j)$. Si $\gamma \neq 0$ realizamos la operación elemental de **Tipo II**: $f_i \to f_i - \frac{\gamma}{\lambda}f_1$. De esta forma obtenemos una matriz con pivote igual a $\lambda$ en la posición $(1, j)$ y ceros por debajo. Si $\gamma = 0$ no se hace nada en la fila $i$.

3. Si la matriz que hemos obtenido es escalonada entonces ya hemos terminado. En caso contrario lo que hacemos es dejar fijadas la primera fila y las primeras $j$ columnas, y con el resto de la matriz comenzar de nuevo el proceso volviendo al paso 1. $\square$

In [55]:
B = np.array([[0,0,2,6],
              [3,6,1,2],
              [3,6,0,-1],
              [0,0,1,5]])

B

array([[ 0,  0,  2,  6],
       [ 3,  6,  1,  2],
       [ 3,  6,  0, -1],
       [ 0,  0,  1,  5]])

In [56]:
def Gauss_method(A):
    A = A.astype(float)  # importante para divisiones
    m, n = A.shape
    
    fila = 0  # fila del pivote actual
    col = 0   # columna actual

    while fila < m and col < n:
        
        # 1. Buscar columna con elemento no nulo
        pivot_row = None
        for i in range(fila, m):
            if A[i, col] != 0:
                pivot_row = i
                break
        
        # Si toda la columna es cero → pasar a la siguiente columna
        if pivot_row is None:
            col += 1
            continue
        
        # Intercambio de filas (Tipo I)
        if pivot_row != fila:
            A[[fila, pivot_row]] = A[[pivot_row, fila]]
        
        # Pivote
        lambda_ = A[fila, col]
        
        # 2. Hacer ceros debajo del pivote (Tipo II)
        for i in range(m):
            if i != fila:
                gamma = A[i, col]
                if gamma != 0:
                    A[i] = A[i] - (gamma / lambda_) * A[fila]
        
        # Avanzar a la siguiente submatriz
        fila += 1
        col += 1
    
    return A

In [57]:
Gauss_method(B)

array([[3., 6., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.],
       [0., 0., 0., 0.]])

Si a la matriz le aplicamos un sucesión diferente de operaciones elementales de filas podemos llegar a otra matriz escalonada diferente. Luego una matriz no es equivalente por filas a una única matriz escalonada.

A menudo nos interesa transformar una matriz dada en un matriz equivalente por filas escalonada reducida. Por ejemplo esto es útil para encontrar las soluciones de un sistema de ecuaciones lineales. 

:::{.callout-note}
## Teorema
Toma matriz es equivalente por filas a una matriz escalonada reducida.
:::


El procedimiento de reducción de a una matriz escalonada reducida usando las operaciones elementales por filas I, II y ## se conoce como **Método de Gauss-Jordan**.

:::{.callout-note}
## Lema
Si $A$ y $B$ son matrices escalonadas reducidas y $A \sim_{f} B$ entonces $A=B$. La matriz escalonada reducida es única.
:::

La **forma de Hermite por filas o forma escalonada reducida** de $A$ es la única matriz escalonada reducida equivalente por filas a $A$. La denotaremos por $H_{f}(A)$

:::{.callout-note}
$A$ y $B$ son equivalente spo filas si y sólo si $H_{f}(A) = H_{f}(B)$
:::