# Algebra lineal básica

## Matrices

Una **Matriz** A de tamaño o de orden $mxn$ es un conjunto de $mxn$ escalares o elementos de un cuerpo $\mathbb{K}$ ordenados en $m$ filas y $n$ columnas de la forma

$$
A = \begin{pmatrix}
        a_{11}  & a_{12} & \cdots & a_{1n}  \\
        a_{21}  & a_{22} & \cdots & a_{2n}  \\
        \vdots  & \vdots & \ddots & \vdots  \\   
        a_{m1}  & a_{m2} & \cdots & a_{mn}   
    \end{pmatrix}
$$

La entrada $(i,j)$ es el elmento de $A$ que se encuentra en la fila $i$ y en la columna $j$, denotado por $a_{ij}$ o $[A]_{ij}$.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [26]:
m1 = np.random.randint(low = 0, high= 9, size= (3,3))
print(m1, m1.shape)

[[4 7 6]
 [4 0 8]
 [4 4 2]] (3, 3)


Definimos $\mathcal{M}_{mxn}$ el conjunto o la familia de matrices de tamaño $mxn$ cuyas entradas o coeficientes son elementos del cuerpo $\mathbb{K}$. En este sentido, una **matriz fila** es una matriz de $\mathcal{M}_{1xn}(\mathbb{K})$ y una **matriz columna** es una matriz de $\mathcal{M}_{mx1}(\mathbb{K})$

$$
A = \begin{pmatrix} 3 & -1 & 1 & 4 \end{pmatrix} 
    \qquad 
B = \begin{pmatrix} 2 \\ 1 \\ 7 \end{pmatrix}
$$

In [28]:
A = np.array([[3,-1,1,4]])
print(A, A.shape)

B = np.array([[2],[1],[7]])
print(B, B.shape)

[[ 3 -1  1  4]] (1, 4)
[[2]
 [1]
 [7]] (3, 1)


In [ ]:
# Por defecto, los arreglos no tienen una orientación definida en numpy

v1 = np.random.randint(100,size = 5) # array sin orientación, unidimensional
print(v1)

[84 59 48 17 92]


In [31]:
# Para tratar con vectores debemos definir su dimensión 

vf = v1.reshape(1,5)
print(vf)
print(vf.T) # Transponiendo la matriz
print(vf.shape)
print(vf.T.shape)

[[84 59 48 17 92]]
[[84]
 [59]
 [48]
 [17]
 [92]]
(1, 5)
(5, 1)


Una **matriz cuadrada** es una matriz con igual número de filas que de columnas, generalmente referida como **matriz de orden n**. Por tanto, $A \in \mathcal{M}_{n} (\mathbb{K})$ es una matriz de orden $n$.

En matrices de orden n podemos definir:

- La diagonal principal de A está formada por las entradas $a_{i,i}$ con $i = 1, \dots , n$
- La traza de A es la suma de los elemento de su diagonal
$$tr(A) = \sum_{i=1}^{n} a_{ii}$$

In [36]:
A = np.random.randint(0,9,size=(3,3))
print(A,A.shape)

diagonal = np.diag(A)
traza = np.trace(A)

print(f'La diagonal principal de A está formada por {diagonal} y su traza tr(A) = {traza} ')



[[2 2 0]
 [8 6 6]
 [0 1 4]] (3, 3)
La diagonal principal de A está formada por [2 6 4] y su traza tr(A) = 12 


La matriz traspuesta de la matriz $A \in \mathcal{M}_{mxn} (\mathbb{K})$ es a matriz $A^{T} \in \mathcal{M}_{nxm} (\mathbb{K})$ cuya entrada $(i,j)$ es igual a la entrada $(j,i)$ de A. Es decir:

$$[A]_{ij} = [A^{T}]_{ji}$$


In [47]:
A = np.random.randint(9,size=(4,3))
print(A, A.shape)
print(f'La transpuesta de A es: \n {A.T, A.shape}')

[[0 5 0]
 [1 4 3]
 [1 4 8]
 [2 4 0]] (4, 3)
La transpuesta de A es: 
 (array([[0, 1, 1, 2],
       [5, 4, 4, 4],
       [0, 3, 8, 0]]), (4, 3))


In [49]:
# Notese que la operación de transposición es idempotente

(A.T).T == A

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Una matriz simétrica es una matriz cuadrada que coincide con su transpuesta, es decir, para $A \in \mathcal{M}_{n} (\mathbb{K})$ se tiene que $A^{T} = A$.

Nótese que dada una matriz $A \in \mathcal{M}_{mxn} (\mathbb{K})$, es posible hallar una matriz simétrica $S \in \mathcal{M}_{mxn} (\mathbb{K})$

$$
\begin{aligned}
S^T &= (A + A^T)^T && \text{(Transponemos ambos lados)} \\
&= A^T + (A^T)^T && \text{(Propiedad distributiva: } (A+B)^T = A^T + B^T) \\
&= A^T + A && \text{(Propiedad de involución: } (A^T)^T = A) \\
&= A + A^T && \text{(Propiedad conmutativa de la suma)} \\
&= S && \text{(Definición original de } S)
\end{aligned}
$$


Una matriz asimétrica es una matriz cuadrada que coincide con su matriz traspuesta cambiada de signo. Esto es, para $A \in \mathcal{M}_{n} (\mathbb{K})$ se tiene que $A^{T} = -A$.

Nótese que dada una matriz $A \in \mathcal{M}_{mxn} (\mathbb{K})$, es posible hallar una matriz asimétrica $K \in \mathcal{M}_{mxn} (\mathbb{K})$

$$
\begin{aligned}
K^T &= (A - A^T)^T && \text{(Aplicamos transposición a ambos lados)} \\
&= A^T - (A^T)^T && \text{(Propiedad distributiva: } (A-B)^T = A^T - B^T) \\
&= A^T - A && \text{(Propiedad de involución: } (A^T)^T = A) \\
&= -(A - A^T) && \text{(Factorizamos el signo negativo)} \\
&= -K && \text{(Sustituimos por la definición original de } K)
\end{aligned}
$$


In [51]:
A = np.random.randint(-10, 11, size=(5, 5)) 

S = A + A.T
K = A - A.T

print(f'Dada una matriz origina \n {A} \n podemos derivar la matriz simétrica \n {S} \n y la matriz asimétrica \n {K}')

Dada una matriz origina 
 [[ 5  4  4  8  1]
 [ 9 -8 -6  8 -4]
 [10 -2 -4  7 -7]
 [ 3  7 -2 10 -9]
 [ 9  4 -4  1 -3]] 
 podemos derivar la matriz simétrica 
 [[ 10  13  14  11  10]
 [ 13 -16  -8  15   0]
 [ 14  -8  -8   5 -11]
 [ 11  15   5  20  -8]
 [ 10   0 -11  -8  -6]] 
 y la matriz asimétrica 
 [[  0  -5  -6   5  -8]
 [  5   0  -4   1  -8]
 [  6   4   0   9  -3]
 [ -5  -1  -9   0 -10]
 [  8   8   3  10   0]]


In [ ]:
# Matriz triangular superior

In [52]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
# La identidad (p.20 pdf)