# Algebra lineal básica

## Matrices

Una **Matriz** A de tamaño o de orden $mxn$ es un conjunto de $mxn$ escalares o elementos de un cuerpo $\mathbb{K}$ ordenados en $m$ filas y $n$ columnas de la forma

$$
A = \begin{pmatrix}
        a_{11}  & a_{12} & \cdots & a_{1n}  \\
        a_{21}  & a_{22} & \cdots & a_{2n}  \\
        \vdots  & \vdots & \ddots & \vdots  \\   
        a_{m1}  & a_{m2} & \cdots & a_{mn}   
    \end{pmatrix}
$$

La entrada $(i,j)$ es el elmento de $A$ que se encuentra en la fila $i$ y en la columna $j$, denotado por $a_{ij}$ o $[A]_{ij}$.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
m1 = np.random.randint(low = 0, high= 9, size= (3,3))
print(m1, m1.shape)

[[6 5 8]
 [6 2 4]
 [2 4 3]] (3, 3)


Definimos $\mathcal{M}_{mxn}$ el conjunto o la familia de matrices de tamaño $mxn$ cuyas entradas o coeficientes son elementos del cuerpo $\mathbb{K}$. En este sentido, una **matriz fila** es una matriz de $\mathcal{M}_{1xn}(\mathbb{K})$ y una **matriz columna** es una matriz de $\mathcal{M}_{mx1}(\mathbb{K})$

$$
A = \begin{pmatrix} 3 & -1 & 1 & 4 \end{pmatrix} 
    \qquad 
B = \begin{pmatrix} 2 \\ 1 \\ 7 \end{pmatrix}
$$

In [3]:
A = np.array([[3,-1,1,4]])
print(A, A.shape)

B = np.array([[2],[1],[7]])
print(B, B.shape)

[[ 3 -1  1  4]] (1, 4)
[[2]
 [1]
 [7]] (3, 1)


In [4]:
# Por defecto, los arreglos no tienen una orientación definida en numpy

v1 = np.random.randint(100,size = 5) # array sin orientación, unidimensional
print(v1)

[61 84 88 42 70]


In [5]:
# Para tratar con vectores debemos definir su dimensión 

vf = v1.reshape(1,5)
print(vf)
print(vf.T) # Transponiendo la matriz
print(vf.shape)
print(vf.T.shape)

[[61 84 88 42 70]]
[[61]
 [84]
 [88]
 [42]
 [70]]
(1, 5)
(5, 1)


Una **matriz cuadrada** es una matriz con igual número de filas que de columnas, generalmente referida como **matriz de orden n**. Por tanto, $A \in \mathcal{M}_{n} (\mathbb{K})$ es una matriz de orden $n$.

En matrices de orden n podemos definir:

- La diagonal principal de A está formada por las entradas $a_{i,i}$ con $i = 1, \dots , n$
- La traza de A es la suma de los elemento de su diagonal
$$tr(A) = \sum_{i=1}^{n} a_{ii}$$

In [6]:
A = np.random.randint(0,9,size=(3,3))
print(A,A.shape)

diagonal = np.diag(A)
traza = np.trace(A)

print(f'La diagonal principal de A está formada por {diagonal} y su traza tr(A) = {traza} ')



[[5 2 5]
 [8 5 0]
 [7 8 4]] (3, 3)
La diagonal principal de A está formada por [5 5 4] y su traza tr(A) = 14 


La matriz traspuesta de la matriz $A \in \mathcal{M}_{mxn} (\mathbb{K})$ es a matriz $A^{T} \in \mathcal{M}_{nxm} (\mathbb{K})$ cuya entrada $(i,j)$ es igual a la entrada $(j,i)$ de A. Es decir:

$$[A]_{ij} = [A^{T}]_{ji}$$


In [7]:
A = np.random.randint(9,size=(4,3))
print(A, A.shape)
print(f'La transpuesta de A es: \n {A.T, A.shape}')

[[2 7 6]
 [5 3 3]
 [4 8 8]
 [7 5 7]] (4, 3)
La transpuesta de A es: 
 (array([[2, 5, 4, 7],
       [7, 3, 8, 5],
       [6, 3, 8, 7]]), (4, 3))


In [8]:
# Notese que la operación de transposición es idempotente

(A.T).T == A

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Una matriz simétrica es una matriz cuadrada que coincide con su transpuesta, es decir, para $A \in \mathcal{M}_{n} (\mathbb{K})$ se tiene que $A^{T} = A$.

Nótese que dada una matriz $A \in \mathcal{M}_{mxn} (\mathbb{K})$, es posible hallar una matriz simétrica $S \in \mathcal{M}_{mxn} (\mathbb{K})$

$$
\begin{aligned}
S^T &= (A + A^T)^T && \text{(Transponemos ambos lados)} \\
&= A^T + (A^T)^T && \text{(Propiedad distributiva: } (A+B)^T = A^T + B^T) \\
&= A^T + A && \text{(Propiedad de involución: } (A^T)^T = A) \\
&= A + A^T && \text{(Propiedad conmutativa de la suma)} \\
&= S && \text{(Definición original de } S)
\end{aligned}
$$


Una matriz asimétrica es una matriz cuadrada que coincide con su matriz traspuesta cambiada de signo. Esto es, para $A \in \mathcal{M}_{n} (\mathbb{K})$ se tiene que $A^{T} = -A$.

Nótese que dada una matriz $A \in \mathcal{M}_{mxn} (\mathbb{K})$, es posible hallar una matriz asimétrica $K \in \mathcal{M}_{mxn} (\mathbb{K})$

$$
\begin{aligned}
K^T &= (A - A^T)^T && \text{(Aplicamos transposición a ambos lados)} \\
&= A^T - (A^T)^T && \text{(Propiedad distributiva: } (A-B)^T = A^T - B^T) \\
&= A^T - A && \text{(Propiedad de involución: } (A^T)^T = A) \\
&= -(A - A^T) && \text{(Factorizamos el signo negativo)} \\
&= -K && \text{(Sustituimos por la definición original de } K)
\end{aligned}
$$


In [15]:
A = np.random.randint(-10, 11, size=(5, 5)) 

S = A + A.T
K = A - A.T

print(f'Dada una matriz origina \n {A} \n podemos derivar la matriz simétrica \n {S} \n y la matriz asimétrica \n {K}')

Dada una matriz origina 
 [[  3   4   0  -1  -2]
 [ -6  -4   1  -8 -10]
 [ -6   5  -1   5  -2]
 [  7   2   8  -9   0]
 [  0   1  -9   0  -8]] 
 podemos derivar la matriz simétrica 
 [[  6  -2  -6   6  -2]
 [ -2  -8   6  -6  -9]
 [ -6   6  -2  13 -11]
 [  6  -6  13 -18   0]
 [ -2  -9 -11   0 -16]] 
 y la matriz asimétrica 
 [[  0  10   6  -8  -2]
 [-10   0  -4 -10 -11]
 [ -6   4   0  -3   7]
 [  8  10   3   0   0]
 [  2  11  -7   0   0]]


Nótese que las entradas situadas en la diagonal principal son iguales a 0. Esta propiedad es válida para cualquier matriz antisimétrica, ¿Por qué?

In [ ]:
K

array([[  0,  10,   6,  -8,  -2],
       [-10,   0,  -4, -10, -11],
       [ -6,   4,   0,  -3,   7],
       [  8,  10,   3,   0,   0],
       [  2,  11,  -7,   0,   0]])

Una matriz triangular superior es una matriz de orden $n$ con todas las entrada situadas por debajo de su diagonal principal iguales a O. Y una matriz triangular inferior es una matriz de orden $n$ con todas las entradas situadas por encima de su diagonal principal iguales a O.

In [28]:
superior = np.triu(A) # upper
inferior = np.tril(A) # lower

print(superior)
print(inferior)

[[  3   4   0  -1  -2]
 [  0  -4   1  -8 -10]
 [  0   0  -1   5  -2]
 [  0   0   0  -9   0]
 [  0   0   0   0  -8]]
[[ 3  0  0  0  0]
 [-6 -4  0  0  0]
 [-6  5 -1  0  0]
 [ 7  2  8 -9  0]
 [ 0  1 -9  0 -8]]


Una matriz diagonal es una matriz de orden n tal que toda entrada ele A situada fuera de su diagonal principal es igual a O. Toda matriz diagonal es triangular superior y triangular inferior.

In [31]:
diagonal = np.diag([1,-5,1,6])
print(diagonal)

[[ 1  0  0  0]
 [ 0 -5  0  0]
 [ 0  0  1  0]
 [ 0  0  0  6]]


La identidad de orden n. que denotamos por J,. es la matriz diagonal de orden n cm1 todas las entradas situadas en la diagonal principal iguales a l.

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Una submatriz ele A es cualquier matriz que se obtenga a partir de A eliminando una o varias de sus filas y o columnas. También se considera a A como una submatriz de A.

In [36]:
A

array([[  3,   4,   0,  -1,  -2],
       [ -6,  -4,   1,  -8, -10],
       [ -6,   5,  -1,   5,  -2],
       [  7,   2,   8,  -9,   0],
       [  0,   1,  -9,   0,  -8]])

In [34]:
A[1:3,1:3]

array([[-4,  1],
       [ 5, -1]])

In [37]:
# Fila completa
A[1,:]

# Columna completa
A[:,2]

array([ 0,  1, -1,  8, -9])

In [38]:
# Etas submatrices son copias, si queremos modificar subA sin modifica A debemos hacer copias

sub_independiente = A[0:2, 0:2].copy()
sub_independiente

array([[ 3,  4],
       [-6, -4]])

In [ ]:
## Operaciones con matrices

