### Funciones de activación

In [2]:
# Elementos introductorios

import numpy as np # Operaciones vectorizadas

In [43]:
# Funciones de activación

def escalon(x):
    if x<0:
        return 0
    else: return 1

In [16]:
def sigmoide(x):
    return 1/(1+np.exp(-x))

### Generación de una muestra de datos aleatoria

In [24]:
# Definamos entradas arbitrarias binarias x,y,z
# Combinación de números binarios de tres digitos

entrada = []
for x in range(0,2):
    for y in range(0,2):
        for z in range(0,2):
            entrada.append([x,y,z])

entrada = np.array(entrada)
entrada

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [23]:
# Si queremos generalizar el proceso para un arreglo de tamaño (2^n,n)
# podemos utilizar prodcutos cartesiano con la función intertools.product()
# A x B = {(a,b): a E A, b E B}
# cardinalidad del conjunto 2^n

from itertools import product

def generar_bits(n):
    entrada = list(product([0,1],repeat = n))
    return np.array(entrada)

In [31]:
entrada = generar_bits(4)
entrada

array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 1],
       [0, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 0, 0],
       [1, 1, 0, 1],
       [1, 1, 1, 0],
       [1, 1, 1, 1]])

### Especifiquemos la red neuronal

In [ ]:
def neurona(input,weight,bias,f):
    return f(np.dot(weight,input.T)+bias)

### Probemos la red con funciones AND y OR

In [40]:
# Primero probemos las salidas que tendrían AND y OR
# Usemos el operador funcional np.all() para AND
# Si todas las entradas son verdaderas, la salida es verdadera

np.all(entrada, axis=1) 

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True])

In [41]:
# Para OR podemos utilizar la función np.any()

np.any(entrada, axis=1)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [39]:
# Evaluemos la función and, cambiemos el tipado para que aparezca en números

and4 = np.all(entrada, axis=1).astype(int)
and4

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

### Probemos nuestra red neuronal

In [44]:
# Empecemos por probar diferentes vectores de pesos

weight = np.array([1,1,1,1])
bias = np.array(1)

neurona(entrada,weight,bias,np.vectorize(escalon))

# Esta red no funciona muy bien, porque no nos da la salida esperada del AND
# ¿Cómo podemos modificarlo para resolver el problema?

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [47]:
# Probemos modificando el bias, que parece ser el que hace que todas sean 1

bias = np.array(-4) # ¿por qué 4?

neurona(entrada,weight,bias,np.vectorize(escalon))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [11]:
# Definamos los pesos aleatorios
# Ya que hay 3 entradas que va a una neurona, debemos tener tres pesos

pesos = np.random.rand(3) # [0,1]

# se recomienda que los pesos estén entre [-1,1], para lo cual realizamos una 
# transformación de la variable pesos

pesos = 2*np.random.rand(3) - 1
pesos

array([ 0.42252924, -0.62797669,  0.09508346])

In [12]:
# Definamos aleatoriamente un bias

bias = 2*np.random.rand(1)-1

In [15]:
# Mostremos las salidas de nuestra neurona

for i in entrada:
    s = neurona(i,pesos,bias)
    print(i)

[0 0 0]
[0 0 1]
[0 1 0]
[0 1 1]
[1 0 0]
[1 0 1]
[1 1 0]
[1 1 1]
