# Introducción a las redes neuronales
1. Neurofisiología elemental
1. Evolución histórica, motivación y origen
1. Concepto de red neuronal artificial
1. Aplicaciones de las redes neuronales

## Neurofisiología elemental
- El cerebro humano es el sistema mas complejo que conoce el hombre
- Realiza diferentes tareas, que permite realizar una comparación computador cerebro

El cerebro funciona a a través de las neuronas, células del cerebro. Estas reciben un impulso electrico a través de unas terminales que denominamos _dentritas_. Ese impulso eléctrico se convierten químicamente en el cuerpo de la neurona. Esto se traslada a los _axones_ que tienen la función de enviar impulsos a otras neuronas. Nuestro cerebro tiene unas 86 mil millones de neuronas.

**Sinápsis** /
La unión entre dos neuronas se conoce como _sinápsis_. Esta se realiza mediante la liberación de sustancias denominadas neurotransmisores. La entrada total de la neurona es la suma de todos los impulsos que recibe.

- Cada neurona envía impulsos a otras neuronas y recibe de muchas otras
- Pueden existir circuitos de realimentación positiva o negativa
- Las conexiones sinápticas pueden ser exitatorias o inhibitorias

**Circuitos neuronales y computación**

¿Cómo se combinan las capacidades de las neuronas (elementos sencillos) para dar al cerebro enormes capacidades?
- La actividad de una neurona es un proceso de todo o nada
- Es preciso un número fijo de sinapsis dentro de un periodo de excitación de la neurona
- La actividad de cualquier sinapsis inhibitoria impide por completo la excitación
- El retorno propio del sistema es el tiempo que requiere la sinapsis
- La estructura de la red no cambia en el tiempo. Eso si pasa con nuestro cerebro, en computación no.


## Evolución histórica
- McCulloch y Pitts en 1943, proponen el modelo de red neuronal con una representación matemática
- En 1949, heeb en su libro _The organizacion of behavior_ explica el aprendizaje mediante la modificación de sinapsis. Este libro es la inspiración para los modelos de aprendizaje y sistemas adaptativos.
- En 1956 Haibt y Duda, propone la primera simulación bien formulada de red neuronal basada en los postulados de Heeb.
- Uttley en 1956 demuestra que una red neuronal con sinapsis cambiante puede aprender a clasificar patrones binarios
- En los años 50, se introduce la idea de memoria asociativa una matriz de aprendizaje
- Von Newman en su libro _The computer an the Brain_ profundiza las diferencias entre cerebros y computadores
- Rossenblat en 1958 introduce el modelo _perceptrón_ para aprendizaje supervisado
- En 1960 Widrow y Hoff introduce el modelo Adeline
- En 1980 se introducen varios modelos de aprendizaje de neuronas entre ellos el aprendizaje competitivo y las redes Hopfield, que son redes realimentadas
- En 1988 Broomhead y Loew describen las redes de funciones de base radial (RBF) que es una alternativa al perceptrón multiplicada
- En las dos últimas décadas las redes neuronales han cobrado importancia por su potencia para solucionar problemas de clasificación y potencialidad para aplicaciones de **machine learning**.

## Red neuronal artificial

- Podemos inspirarnos en el funcionamiento del cerebro para realizar computación
- Utilizamos la neurona como elemento de computación
- Cada neurona es independiente y funciona como un elemento de procesamiento individual
- Cada neurona se conecta con otra (con sus entradas o sus salidas)

**Neurona artificial**

- Cada neurona tiene unas entradas y unas salidas
- Las salidas de unas neuronas pueden ser las entradas de otras neuronas
- Utilizamos **conexiones ponderadas**

- Si se ajustan adecuadamente los pesos se tendrá un sistema robusto
- Puede reconocer ciertos patrones, así estos cambien un poco
- Tiene tolerancia al ruido inherente (son modelos robustos)
- Las redes neuronales son **soluciones ad-hoc**. Cada problema requiere una red neuronal diferente.

**¿Qué vamos a estudiar?**

- Representación de la red neuronal (modelo matemático)
- Cómo reaccionan las redes a diferentes entradas (funciones de activación)
- Estructuración de las redes neuronales (arquitecturas)


* **Recomendación:** programa especializado: aprendizaje profundo [Coursera]

# Propiedades redens neuronales
- Aprendizaje adaptativo
- Generalización
- Naturaleza para propósito no-lineal
- Auto-organización
- Paralelismo masivo (cada neurona trabaja de forma independiente)
- Robustez y tolerancia a ruido

## Modelo no lineal

- Cada neurona recibe un conjunto de señales discretas o continuas
- Estas señales se ponderan o integran
- Cada conexión tiene un peso sináptico
- Los pesos representan el conocimiento 
- Estos pesos se ajustan con algoritmos de aprendizaje

Una rede neuronal tiene:
- Un conjunto _m_ de señales de entrada
- un conjunto de sinápsis $w_ij$ donde i indica la i-ésima entrada de la neurona j
- Un umbral o sesgo b, puede ser positivo o negativo
- Las entradas son sumadas o integradas, tomando en cuenta sus respectivos pesos
- Se tienen una función de activación $\sigma$ que describe el funcionamiento de la neurona

El modelo lo podemos escribir así

$$z = \varphi(\sum_{i=1}^{m} w_{i}x_{i}+b)$$

Para i : 'número de neuronas'. En su forma vectorial

$$z = \varphi(WX^{T}+b)$$

## Funciones de activación

Con una función:
1. Función lineal: suele variar entre 0 y 1 o -1 y 1
1. Función escalón: salida bivaluada $\varphi(x) = 0 si x < 0 \atop 1 si x >= 0 $
1. Función sigmoidea: transformación no lineal de la entrada [Es la función mas usada dado que la derivada se escribe en terminos de ella misma]

$$\varphi(x) = \frac{1}{1+e^{-ax}}$$

en esta especificación, suele utilizarse a=1.

1. Hay otas que se usan bastante como la tangente hiperbólica. No tan famosa como la sigmoidea.

Las salidas están entre 0 (estimulo inhibitorio) y 1 (excitatoria).

In [8]:
import numpy as np

In [1]:
# Definamos una función de activación, en este caso será una función escalon
def activacion(x):
    return 0 if x < 0 else 1

In [2]:
def neurona(ent,pesos,bias):
    entrada_neta = np.dot(pesos,ent.T)+ bias #Vease la fromulación matemática de una neurona
    return activacion(entrada_neta)

In [16]:
entrada = np.array([[x,y,z] for x in range(0,2) for y in range(0,2) for z in range(0,2)])

In [17]:
entrada # Combinación de tres para valores binarios

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [23]:
# Los pesos deben estar normalizados entre [-1,1], los voy a crear aleatoriamente
# Tambien creare el bias

pesos = 2*np.random.rand(3)-1
print(pesos)

bias = 2*np.random.rand(1)-1
print(bias)

[ 0.32909444  0.64439812 -0.63859375]
[-0.28548209]


In [24]:
# Operamos la neurona: para cada elemento del array, operamos la función neurona e imprimimos el arreglo y la salida
for e in entrada:
    s = neurona(e,pesos,bias)
    print(e,s)

[0 0 0] 0
[0 0 1] 0
[0 1 0] 1
[0 1 1] 0
[1 0 0] 1
[1 0 1] 0
[1 1 0] 1
[1 1 1] 1


In [30]:
# El funcionamiento interno es este
1*pesos[0]+1*pesos[1]+0*pesos[2] #es mayor que 0, nos da como salida 1

0.9734925566817656

In [31]:
# La función de activación puede ser cualquiera, imaginemos la función or

salida = list(map(
    lambda e: e[0] or e[1]or e[2],
    entrada
))
salida

[0, 1, 1, 1, 1, 1, 1, 1]

In [33]:
#Como mi función es escalonada, debo darle pesos para que reconozca la función or. Esto lo puedo lograr con pesos =1 y un bias =-1
#Si al menos un elementos es 1, ya se cumple la función or

pesos = np.array([1,1,1]) 
bias = np.array([-1])

for e,t in zip(entrada,salida):
    s = neurona(e,pesos,bias)
    print(e,t,s)

array([1, 1, 1])

In [38]:
# ¿Cómo haríamos ahora para reconocer la función AND?

salidaAnd = list(map(
    lambda e: e[0] or e[1]or e[2],
    entrada
))


pesosAnd = np.array([1,1,1]) 
biasAnd = np.array([-3])

for e,t in zip(entrada,salidaAnd):
    s = neurona(e,pesosAnd,biasAnd) #Acá se ve la importancia del bias
    print(e,t,s)

[0 0 0] 0 0
[0 0 1] 1 0
[0 1 0] 1 0
[0 1 1] 1 0
[1 0 0] 1 0
[1 0 1] 1 0
[1 1 0] 1 0
[1 1 1] 1 1


## El aprendizaje

El objetivo del entrenamiento de una red es ajustar esos pesos para que se parezca a la salida deseada. Esto se conoce como entrenamiento. Este aprendizaje en las redes neuronales se puede modelar así:

$$w(t+1) = w(t) + \triangle w(t)$$

El peso $\triangle w(t)$ se va ajustando $t$ veces de tal forma que se minimice el error de la salida.

Hay diferentes tipos de aprendizajes

### Aprendizaje supervisado
- basado en la comparación entre la salida actual y la deseada
- Los pesos se ajustan de acuerdo a patrón de entrenamiento 
- Existe un criterio de parada para el procesos de aprendizaje de acuerdo a la medida del error

$$E = \frac{1}{N} \sum_{p=1}^N (Y_d - Y_c)^2$$

### Aprendizaje no supervisado
- No hay valores objetivos
- Está basado en las correlaciones entre la entrada y patrones significantes en el aprendizaje
- Se requiere un método de parada

### Aprendizaje por refuerzo
- Es un caso especial del aprendizaje supervisado
- La salida deseada es desconocida
- Se castiga una mala salida y se premia una buena salida (algoritmos genéticos)

## Clases de arquitecturas

**Redes de una capa sin ciclos**
- Es la forma mas simple
- Consiste en una capa que recibe la entrada y emite una o más salidas

**Multicapa sin ciclos**
- Tiene una capa de entrada
- Tiene capas ocultas
- Tiene capas de salida

**Redes recurrentes**
- Tiene una esctructura monocapa o multicapa
- La salida se conecta a las entradas, pero estas tienen un retardo

In [43]:
# Vamos a programas una neurona con 3 neuronas en la capa de entrada, dos en la primera capa oculta, 3 en la tercera capa oculta y una en la capa de salida. Cada neurona tendrá su propio bias.

#Representemos la primera capa oculta (2 neuronas que tiene 3 entradas)

activacion_v = np.vectorize(activacion) #Convierte la función de activación en una vactorizada. Así evalúa cada elemento sin el uso de map.

def redneuronal(ent,pesosC1,biasC1,
                pesosC2,biasC2,
                pesosCS,biasCS):
    # Capa oculta 1
    entC1 = np.dot(pesosC1,ent.T)+ biasC1.T #producto de matrices con np.dot()
    salC1 = activacion_v(entC1)
    # Capa oculta 2
    entC2 = np.dot(pesosC2,salC1)+ biasC2.T
    salC2 = activacion_v(entC2)
    #Capa de salida
    entCS = np.dot(pesosCS,salC2)+biasCS.T
    return activacion_v(entCS)

In [44]:
# Probemos nuestra red con algunos pesos aleatorios

pesosC1 = np.random.rand(2,3)
biasC1 = np.random.rand(2)
pesosC2 = np.random.rand(3,2)
biasC2 = np.random.rand(3)
pesosCS = np.random.rand(1,3)
biasCS = np.random.rand(1)

for i in entrada:
    sal = redneuronal(i,pesosC1,biasC1,
                pesosC2,biasC2,
                pesosCS,biasCS)
    print(i,sal)

[0 0 0] [1]
[0 0 1] [1]
[0 1 0] [1]
[0 1 1] [1]
[1 0 0] [1]
[1 0 1] [1]
[1 1 0] [1]
[1 1 1] [1]
