# Algoritmos básicos de redes neuronales

**Carpeta de trabajo**: https://drive.google.com/drive/u/0/folders/1Nl-8QVK1PGDCIePi6-M60mHthSsbXMbP

**Videos:** https://www.youtube.com/watch?v=MyrjuBGyr90&list=PLi3X2PHYk7zQUnOITsQJckF1_yHDsJjqT&index=4 

## Perceptrón:
- Fue introducido por Rossenblar a finales de los años 50
- Se inspira en los procesos de aprendizaje de los animales en los cuales la información va atravesando diferentes capas de neuronas
- Es un modelo unidireccional, compuesto por dos capas de neuronas, una de entrada y otra de salida
- La operación de este tipo puede darse con _n_ neuronas de entrada y _m_ de salida.

### Definición
- Las neuronas de entrada no realizan ningún computo
- Se consideran señales discretas 0 o 1
- La operación para _n_ neuoronas de entrada y _m_ de salida puede considerarse así:
$$y_i = H(\sum_{j=1}^{n}w_{ij}x_{j}-\Theta_{i}), \forall i, 1<= i <=m$$

Donde H(x) es la función escalón. $w_{ij}$ los pesos, x_{j} las entradas que recibe cada estimulo y $\Theta_{i}$ es el umbral.

- El perceptrón permite clasificar dos conjuntos linealmente separables en un plano o hiperplano. 
- La respuesra de la neurona es 1 si pertenece a la clase o 0 si no pertenece

**Ejemplo de prueba**
- Sea una neurona tipo perceptrón con entrada $x_1$ y $x_2$
- Entonces la operación se define como

$$y = H(w_1 x_1 + w_2 x_2 - \Theta)$$

En este caso la función es lineal, muestra entonces una recta que divide el plano en dos regiones. Por lo tanto, se requiere que el problema de clasificación (binaria) requiere una solución lineal: or y and se pueden resolver con perceptrón, pero xor no. Podría resolver problemas mas complejos, como xor, pero para ello requiero mas de una capa. Esto es un perceptrón de dos capas. La complejidad se puede ampliar con las capas, permitiendo regiones convexas. 

## Algoritmo de aprendizaje del perceptrón

- La idea principal del entrenamiento es es minimizar los errores, esto es la diferencia entre la estimación $\hat{y}$ y lo observado $y$.
- Vamos a introducir una tasa de aprendizaje _n_ que indica el ritmo de aprendizaje. Si la tasa de aprendizaje es mul alta es posible que no se encuentre una solución, ya que no logra una solución convergente y empieza a oscilar. Si es muy pequeño, el entrenamiento se demoraría demasiado. 
- Dados unos patrones $x^u$, salidas obtenidas $y^u$ y salidas deseadas $t^u$
- Los pesos iniciales son aleatorios entre -1 y 1
- Se examina cada patrón y aplicamos la relación de cambio

$$\triangle w_{ij}^{u}(t)=n(t_i ^u - y_i ^u)x_j ^u$$

A esto se le conoce como **regla del perceptrón**

La idea es ajustar los pesos para poder realizar la separación lineal que nos interesa. Acá estamos considerando un problema de clasificación lineal, que son los problemas que resuelven los **perceptrónes monocapa**

### Algoritmo de aprendizaje

Desarrollaremos un algoritmo de clasificación entre 0 y 1.

1. Inicializamos los pesos aleatoriamente entre [-1,1]
2. Para el estado _t_, $\hat{y}$ o salida deseada. Calcular:

$$\hat{y} = t^{u}(k)=H(\sum_{j=1}^n (x_j j)-\Theta)$$

3. Coregir pesos sinápticos (si $\hat{y} \neq y$)

$$w_{j} = w_{j} + n[\hat{y} - y]x$$

4. Para si no se han modificado los pesos en los últimos p patrones o se ha llegado a un número de iteraciones especificado.

In [1]:
# Algoritmo perceptrón en Python

import numpy as np

### Definimos la función de activación

In [45]:
# Definimos función de activación escalonada, la cual deseamos que opere sobre estructuras iterables

# Implementación explícita sobre arreglos
def activacion(x):
    salida = []
    for i in x:
        salida.append(1 if i>= 0 else 0) # Operador ternario
    return salida

# Implementación vectorizada

def activacion_no_vec(x):
    return 1 if x>= 0 else 0 
# Vectorización de la función de activación
activacion_v = np.vectorize(activacion_no_vec)


In [16]:
# Veamos ejemplos de como operaría la función escalonada

random_list = np.random.randint(-10,10,10)

print(f'Implementación explícita con bucles: {activacion(random_list)}') #lista
print(f'Implementación vectorizada: {activacion_v(random_list)}') # np.array

Implementación explícita con bucles: [1, 0, 1, 0, 1, 0, 1, 1, 0, 1]
Implementación vectorizada: [1 0 1 0 1 0 1 1 0 1]


### Definimos la neurona

In [46]:
def neurona(input,weight,bias):
    net = np.dot(weight,input.T)-bias 
    return activacion_v(net) 

In [66]:
# La salida es un escalar, juguemos con valores de i,w y b para ver la cuestión

neurona(np.array([-1,2,-3,3.9]),np.array([1,1,1,1]),1)

array(1)

### Algoritmo perceptrón

In [43]:
def perceptron(input, output, n, n_patterns=10, max_it=1000):
    # Inicializo los pesos y el sesgo aleatoriamente
    weights = 2 * np.random.rand(input.shape[1]) - 1  # El producto por dos y menos 1 es para que quede entre el intervalo deseado [-1,1]
    bias = 2 * np.random.rand(1) - 1

    p = 0 # Número de patrones clasificados correctamente en una iretación
    it = 0 # Iteraciones
    loss = [] # Error cuadratico medio sum(e^2)/n

    # Condición de terminación del entrenamiento
    while (p <= n_patterns and it < max_it):
        it += 1
        p = 0  # Reinicio el contador de patrones clasificados correctamente
        for i, t in zip(input, output): # zip agrupa elementos en parejas ordenados (input[0], output[0]), por ejemplo. esta forma del for es común con parejas ordenadas
            y = neurona(i, weights, bias) # Salida del perceptron 
            error = t - y[0]
            error_it += error**2
            p+=1

            # Lo que sigue es el algoritmo de correción

            if error != 0:
                p = 0
                weights = weights + n * error * inp
                bias = bias + n * error * (-1)

        error_it /= ents.shape[0]
        loss.append(error_it) 

    return weights, bias, loss

### Prueba de nuestro perceptron

In [67]:
# Generemos un data set de prueba

X = np.array([[x,y,z,w,a] for x in range(0,2)
                   for y in range(0,2)
                   for z in range(0,2)
                   for w in range(0,2)
                   for a in range(0,2)]
)

# Probemos primero con la función or

y = np.array(list(map(lambda e: e[0] or e[1] or e[2] or e[3] or e[4],ents)))

In [37]:
# Visualización del conjunto de datos

list(zip(entr, sali))


32

In [40]:
# Definimos los hiperparámetros del modelo
n = 0.5 # factor de aprendizaje
max_it = 200 
p = len(sali) #Cuántos patrones debe contar (debe contar que todos estén bien, por eso es 2**5). No hay error.
weight,bias = perceptron(entr,sali,n,p,max_it)

In [44]:
for ent, sal in zip(entr,sali):
    print(ent,sal,neurona(ent,weight,bias)[0])

[0 0 0 0 0] 0 1
[0 0 0 0 1] 1 1
[0 0 0 1 0] 1 1
[0 0 0 1 1] 1 1
[0 0 1 0 0] 1 1
[0 0 1 0 1] 1 1
[0 0 1 1 0] 1 1
[0 0 1 1 1] 1 1
[0 1 0 0 0] 1 1
[0 1 0 0 1] 1 1
[0 1 0 1 0] 1 1
[0 1 0 1 1] 1 1
[0 1 1 0 0] 1 1
[0 1 1 0 1] 1 1
[0 1 1 1 0] 1 1
[0 1 1 1 1] 1 1
[1 0 0 0 0] 1 1
[1 0 0 0 1] 1 1
[1 0 0 1 0] 1 1
[1 0 0 1 1] 1 1
[1 0 1 0 0] 1 1
[1 0 1 0 1] 1 1
[1 0 1 1 0] 1 1
[1 0 1 1 1] 1 1
[1 1 0 0 0] 1 1
[1 1 0 0 1] 1 1
[1 1 0 1 0] 1 1
[1 1 0 1 1] 1 1
[1 1 1 0 0] 1 1
[1 1 1 0 1] 1 1
[1 1 1 1 0] 1 1
[1 1 1 1 1] 1 1


In [27]:
[[x,y] for x in range(0,2) for y in range(0,2)]

[[0, 0], [0, 1], [1, 0], [1, 1]]